
version: '3'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db/bank_customer_portrait
      - JWT_SECRET_KEY=production-secret-key-please-change
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bank_customer_portrait
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
